version: '3.8'


services:
  app:
    build: .
    command: yarn dev
    links:
      - db
      - redis
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/app


  db:
    container_name: 'database-node'
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=teste
      - MYSQL_PASSWORD=1298
      - MYSQL_ROOT_PASSWORD=1298
      - MYSQL_DATABASE=reload
      - TZ=America/Sao_Paulo
      # - MYSQL_USER=${MYSQL_USER}
      # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      # - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      # - MYSQL_DATABASE=${MYSQL_DATABASE}




  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "${REDIS_POST}:${REDIS_POST}"




